/**
 * Oh My Keymint Modded — WebUI Main Logic
 *
 * Features:
 * - Package Name Management (scope/scoop + deny list) — auto-syncs to injector.toml
 * - Keybox Import (URL download, paste content, file browser via shell)
 * - Service Control (restart daemons, kill GMS)
 * - Module Status Dashboard
 */
import { exec, spawn, toast, enableEdgeToEdge } from './assets/kernelsu.js';

/* ===== Constants ===== */
const INJECTOR_PATH = '/data/adb/modules/oh_my_keymint/injector.toml';
const KEYBOX_PATH = '/data/adb/modules/oh_my_keymint/keybox.xml';
const KEYBOX_BACKUP_PATH = '/data/adb/modules/oh_my_keymint/keybox_backup.xml';
const OMK_DATA_KEYBOX = '/data/misc/keystore/omk/keybox.xml';
const STATE_DIR = '/data/adb/omk';

/* ===== State ===== */
let currentScoop = [];
let currentDeny = [];

/* ===== Utilities ===== */

function log(msg, level = 'info') {
    const logEl = document.getElementById('logOutput');
    const emptyEl = logEl.querySelector('.log-empty');
    if (emptyEl) emptyEl.remove();
    const line = document.createElement('div');
    line.className = `log-line log-${level}`;
    const ts = new Date().toLocaleTimeString();
    line.textContent = `[${ts}] ${msg}`;
    logEl.appendChild(line);
    logEl.scrollTop = logEl.scrollHeight;
}

function showToast(msg, duration = 2500) {
    const container = document.getElementById('toastContainer');
    const el = document.createElement('div');
    el.className = 'toast';
    el.textContent = msg;
    container.appendChild(el);
    setTimeout(() => {
        el.classList.add('out');
        setTimeout(() => el.remove(), 300);
    }, duration);
}

async function sh(cmd) {
    const result = await exec(cmd, {});
    return result;
}

async function readFile(path) {
    const r = await sh(`cat ${path} 2>/dev/null || echo '__EMPTY__'`);
    if (r.stdout && r.stdout.trim() === '__EMPTY__') return '';
    if (r.errno !== 0) return '';
    return r.stdout || '';
}

async function writeFile(path, content) {
    const b64 = btoa(unescape(encodeURIComponent(content)));
    return await sh(`echo "${b64}" | base64 -d > ${path}`);
}

async function fileExists(path) {
    const r = await sh(`[ -f "${path}" ] && echo "yes" || echo "no"`);
    return r.stdout.trim() === 'yes';
}

/* ===== Keybox XML validation helper ===== */
function looksLikeKeybox(text) {
    return text.includes('<KeyBox') || text.includes('<keybox') ||
           text.includes('<Keybox') || text.includes('<AndroidAttestation') ||
           text.includes('<AndroidAttestation>');
}

/* ===== Injector TOML Parser / Writer ===== */

function parseInjectorToml(text) {
    const result = {
        scoop: [],
        main: { enabled: true, log_level: 'debug' },
        filter: { enabled: true, deny_packages: [], block_android_package: true, allow_unknown_package: false },
        intercept: {}
    };
    const scoopMatch = text.match(/^scoop\s*=\s*\[([\s\S]*?)\]/m);
    if (scoopMatch) { const items = scoopMatch[1].match(/

"([^"]+)"/g); if (items) result.scoop = items.map(s => s.replace(/"/g, '')); }
    const denyMatch = text.match(/deny_packages\s*=\s*\[([\s\S]*?)\]/m);
    if (denyMatch) { const items = denyMatch[1].match(/

"([^"]+)"/g); if (items) result.filter.deny_packages = items.map(s => s.replace(/"/g, '')); }
    const enabledMatch = text.match(/enabled\s*=\s*(true|false)/);
    if (enabledMatch) result.main.enabled = enabledMatch[1] === 'true';
    const logMatch = text.match(/log_level\s*=\s*"([^"]+)"/);
    if (logMatch) result.main.log_level = logMatch[1];
    const blockMatch = text.match(/block_android_package\s*=\s*(true|false)/);
    if (blockMatch) result.filter.block_android_package = blockMatch[1] === 'true';
    const unknownMatch = text.match(/allow_unknown_package\s*=\s*(true|false)/);
    if (unknownMatch) result.filter.allow_unknown_package = unknownMatch[1] === 'true';
    const interceptSections = text.match(/\[intercept\]([\s\S]*?)(?=\n\[|$)/);
    if (interceptSections) {
        for (const line of interceptSections[1].split('\n')) {
            const kv = line.match(/^\s*(\w+)\s*=\s*(true|false)/);
            if (kv) result.intercept[kv[1]] = kv[2] === 'true';
        }
    }
    return result;
}

function buildInjectorToml(config) {
    return `# Oh My Keymint Injector Configuration
# Generated by WebUI

scoop = [
${config.scoop.map(p => `  "${p}",`).join('\n')}
]

[main]
enabled = ${config.main.enabled}
log_level = "${config.main.log_level}"

[filter]
enabled = ${config.filter.enabled !== false}
deny_packages = [
${(config.filter.deny_packages || []).map(p => `  "${p}",`).join('\n')}
]
block_android_package = ${config.filter.block_android_package}
allow_unknown_package = ${config.filter.allow_unknown_package}

[intercept]
get_security_level = true
get_key_entry = true
update_subcomponent = true
list_entries = true
delete_key = true
grant = true
ungrant = true
get_number_of_entries = true
list_entries_batched = true
get_supplementary_attestation_info = true
`;
}

/* ===== Core: sync state to injector.toml ===== */

async function syncToFile() {
    const content = await readFile(INJECTOR_PATH);
    let config;
    if (content) {
        config = parseInjectorToml(content);
    } else {
        config = { scoop: [], main: { enabled: true, log_level: 'debug' }, filter: { enabled: true, deny_packages: [], block_android_package: true, allow_unknown_package: false }, intercept: {} };
    }
    config.scoop = [...currentScoop];
    config.filter.deny_packages = [...currentDeny];
    const toml = buildInjectorToml(config);
    const r = await writeFile(INJECTOR_PATH, toml);
    if (r.errno === 0) { log(__('log.synced'), 'success'); }
    else { log(__('log.sync_failed', {error: r.stderr}), 'error'); }
}

/* ===== Package Name Management ===== */

async function loadInjectorConfig() {
    const content = await readFile(INJECTOR_PATH);
    if (!content) {
        log(__('log.read_failed'), 'error');
        currentScoop = ['io.github.vvb2060.keyattestation', 'com.google.android.gsf', 'com.google.android.gms', 'com.android.vending', 'com.eltavine.duckdetector'];
        currentDeny = [];
        return;
    }
    const config = parseInjectorToml(content);
    currentScoop = config.scoop;
    currentDeny = config.filter.deny_packages || [];
    log(__('log.read_count', {scoop: currentScoop.length, deny: currentDeny.length}));
}

function renderPkgList(filter = '') {
    const listEl = document.getElementById('pkgList');
    const numEl = document.getElementById('scoopNum');
    const denyNumEl = document.getElementById('denyNum');
    let items = currentScoop.map(pkg => ({ name: pkg, denied: currentDeny.includes(pkg) }));
    if (filter) { const f = filter.toLowerCase(); items = items.filter(i => i.name.toLowerCase().includes(f)); }
    if (items.length === 0) { listEl.innerHTML = '<div class="loading-spinner">' + __('scope.no_match') + '</div>'; numEl.textContent = currentScoop.length; denyNumEl.textContent = currentDeny.length; return; }
    listEl.innerHTML = items.map(item => `
        <div class="pkg-item">
            <span class="pkg-name">${item.denied ? '<span class="pkg-deny-badge">' + __('scope.deny_badge') + '</span>' : ''}${item.name}</span>
            <div class="pkg-actions">
                ${item.denied ? `<button class="btn-icon-small" data-action="unban" data-pkg="${item.name}" title="` + __('scope.unban_title') + `">✅</button>` : `<button class="btn-icon-small" data-action="ban" data-pkg="${item.name}" title="` + __('scope.ban_title') + `">⛔</button>`}
                <button class="btn-icon-small remove" data-action="remove" data-pkg="${item.name}" title="` + __('scope.remove_title') + `">🗑️</button>
            </div>
        </div>
    `).join('');
    numEl.textContent = currentScoop.length;
    denyNumEl.textContent = currentDeny.length;
    listEl.querySelectorAll('[data-action]').forEach(btn => {
        btn.addEventListener('click', async (e) => {
            const action = btn.dataset.action;
            const pkg = btn.dataset.pkg;
            if (action === 'remove') {
                currentScoop = currentScoop.filter(p => p !== pkg);
                currentDeny = currentDeny.filter(p => p !== pkg);
                renderPkgList(document.getElementById('pkgSearch').value);
                updateStats();
                showToast(__('toast.pkg_removed', {pkg: pkg}));
                await syncToFile();
            } else if (action === 'ban') {
                if (!currentDeny.includes(pkg)) { currentDeny.push(pkg); renderPkgList(document.getElementById('pkgSearch').value); updateStats(); showToast(__('toast.pkg_denied', {pkg: pkg})); await syncToFile(); }
            } else if (action === 'unban') {
                currentDeny = currentDeny.filter(p => p !== pkg);
                renderPkgList(document.getElementById('pkgSearch').value);
                updateStats();
                showToast(__('toast.pkg_undenied', {pkg: pkg}));
                await syncToFile();
            }
        });
    });
}

function updateStats() {
    document.getElementById('scoopCount').textContent = `${__('scope.scoop_count')}: ${currentScoop.length}`;
    document.getElementById('denyCount').textContent = `${__('scope.deny_count')}: ${currentDeny.length}`;
}

async function applyScope() {
    log(__('log.applying_scope'));
    await syncToFile();
    showToast(__('toast.config_updated'));
}

async function resetToAllApps() {
    log(__('log.collecting_apps'));
    const r = await exec('pm list packages | sed "s/package://g" | sort', {});
    if (r.errno !== 0) { log(__('log.app_list_failed'), 'error'); return; }
    const allPkgs = r.stdout.trim().split('\n').filter(p => p);
    currentScoop = allPkgs;
    currentDeny = [];
    renderPkgList(document.getElementById('pkgSearch').value);
    updateStats();
    log(__('log.added_apps', {count: allPkgs.length}), 'success');
    showToast(__('toast.pkg_count_added', {count: allPkgs.length}));
    await syncToFile();
}

/* ===== Keybox Management ===== */

async function checkKeyboxStatus() {
    const exists = await fileExists(KEYBOX_PATH);
    const backupExists = await fileExists(KEYBOX_BACKUP_PATH);
    document.getElementById('kbCurrent').textContent = exists ? __('keybox.exists') : __('keybox.not_exists');
    document.getElementById('kbCurrent').style.color = exists ? 'var(--color-primary)' : 'var(--color-error)';
    document.getElementById('kbBackup').textContent = backupExists ? __('keybox.backed_up') : __('keybox.no_backup');
    document.getElementById('kbBackup').style.color = backupExists ? 'var(--color-primary)' : 'var(--color-on-surface-variant)';
    if (exists) {
        const r = await sh(`wc -c < ${KEYBOX_PATH}`);
        const size = parseInt(r.stdout.trim() || '0');
        document.getElementById('kbFormat').textContent = size > 500 ? `✅ ${(size/1024).toFixed(1)}KB` : __('keybox.small') + ` (${size}B)`;
    }
}

async function downloadKeyboxFromUrl(url) {
    if (!url) { showToast(__('keybox.toast_invalid_url')); return; }
    const progressEl = document.getElementById('downloadProgress');
    const fillEl = document.getElementById('dlProgressFill');
    const textEl = document.getElementById('dlProgressText');
    progressEl.classList.remove('hidden');
    fillEl.style.width = '30%';
    textEl.textContent = __('keybox.downloading');
    log(__('log.downloading_keybox', {url: url}));
    await exec(`curl -sL "${url}" -o /data/local/tmp/new_keybox.xml 2>/dev/null || wget -qO /data/local/tmp/new_keybox.xml "${url}" 2>/dev/null`, {});
    fillEl.style.width = '70%';
    textEl.textContent = __('keybox.verifying');
    const check = await exec(`[ -s /data/local/tmp/new_keybox.xml ] && echo "OK" || echo "EMPTY"`, {});
    if (check.stdout.trim() === 'OK') {
        fillEl.style.width = '90%';
        textEl.textContent = __('keybox.deploying');
        await sh(`cp /data/local/tmp/new_keybox.xml ${KEYBOX_PATH} 2>/dev/null`);
        await sh(`mkdir -p /data/misc/keystore/omk && cp /data/local/tmp/new_keybox.xml ${OMK_DATA_KEYBOX} 2>/dev/null`);
        await sh(`cp ${KEYBOX_PATH} ${KEYBOX_BACKUP_PATH} 2>/dev/null`);
        fillEl.style.width = '100%';
        textEl.textContent = __('keybox.deploy_done');
        log(__('log.keybox_deployed'), 'success');
        showToast(__('keybox.toast_imported'));
        await checkKeyboxStatus();
        setTimeout(() => { progressEl.classList.add('hidden'); fillEl.style.width = '0%'; }, 1500);
    } else {
        textEl.textContent = __('keybox.download_failed');
        fillEl.style.width = '0%';
        fillEl.style.backgroundColor = 'var(--color-error)';
        log(__('log.keybox_download_failed'), 'error');
        showToast(__('keybox.toast_download_failed'));
        setTimeout(() => { progressEl.classList.add('hidden'); fillEl.style.width = '0%'; fillEl.style.backgroundColor = ''; }, 2000);
    }
    await sh('rm -f /data/local/tmp/new_keybox.xml');
}

async function pasteKeybox(content) {
    if (!content.trim()) { showToast(__('keybox.toast_paste')); return; }
    if (!looksLikeKeybox(content)) { showToast(__('keybox.toast_not_keybox')); return; }
    log(__('log.importing_keybox'));
    await writeFile('/data/local/tmp/new_keybox.xml', content);
    await sh(`cp /data/local/tmp/new_keybox.xml ${KEYBOX_PATH} 2>/dev/null`);
    await sh(`mkdir -p /data/misc/keystore/omk && cp /data/local/tmp/new_keybox.xml ${OMK_DATA_KEYBOX} 2>/dev/null`);
    await sh(`cp ${KEYBOX_PATH} ${KEYBOX_BACKUP_PATH} 2>/dev/null`);
    await sh('rm -f /data/local/tmp/new_keybox.xml');
    log(__('log.keybox_imported'), 'success');
    showToast(__('keybox.toast_imported'));
    document.getElementById('keyboxTextArea').value = '';
    await checkKeyboxStatus();
}

/* ===== Keybox File Browser (via shell ls) ===== */

let fileBrowserPath = '/storage/emulated/0';
let fileBrowserSelectedPath = null;
let fileBrowserEntries = [];

async function listDir(path) {
    const nameR = await exec(`cd "${path}" 2>/dev/null && ls -1 2>/dev/null`, {});
    if (nameR.errno !== 0 || !nameR.stdout.trim()) return [];
    const names = nameR.stdout.trim().split('\n').filter(n => n && n !== '.' && n !== '..');
    const typeR = await exec(`cd "${path}" 2>/dev/null && ls -1F 2>/dev/null`, {});
    const typeLines = typeR.stdout.trim().split('\n').filter(Boolean);
    const typeMap = {};
    for (const line of typeLines) {
        if (line.endsWith('/')) typeMap[line.slice(0, -1)] = 'd';
        else if (line.endsWith('*')) typeMap[line.slice(0, -1)] = 'f';
        else typeMap[line] = 'f';
    }
    const entries = [];
    for (const name of names.slice(0, 500)) {
        const isDir = typeMap[name] === 'd';
        const escaped = `"${path}/${name}"`;
        let size = 0;
        if (!isDir) {
            const sizeR = await exec(`stat -c%s ${escaped} 2>/dev/null || wc -c < ${escaped} 2>/dev/null`, {});
            size = parseInt(sizeR.stdout.trim()) || 0;
        }
        entries.push({ name, isDir, size, fullPath: `${path}/${name}` });
    }
    return entries;
}

function renderFileBrowser(dir) {
    if (dir === '/storage/emulated/0' || dir === '/storage/emulated') dir = '/storage/emulated/0';
    fileBrowserPath = dir;
    document.getElementById('fileBrowserPath').textContent = dir;
    const listEl = document.getElementById('fileBrowserList');
    listEl.innerHTML = '<div class="loading-spinner">' + __('scope.loading') + '</div>';
    fileBrowserSelectedPath = null;
    document.getElementById('fileBrowserSelect').disabled = true;
    document.getElementById('fileBrowserSelected').textContent = __('keybox.no_selection');
    (async () => {
        const all = await listDir(dir);
        fileBrowserEntries = all;
        const filter = document.getElementById('fileBrowserSearch').value.toLowerCase();
        let filtered = all;
        if (filter) filtered = all.filter(e => e.name.toLowerCase().includes(filter));
        if (filtered.length === 0) { listEl.innerHTML = '<div class="loading-spinner">' + __('keybox.empty_dir') + '</div>'; return; }
        listEl.innerHTML = filtered.map(entry => `
            <div class="modal-file-item ${entry.isDir ? 'dir-item' : ''}" data-path="${entry.fullPath}" data-name="${entry.name}" data-dir="${entry.isDir}">
                <span class="file-icon">${entry.isDir ? '📁' : '📄'}</span>
                <span class="file-name-text">${entry.name}</span>
                <span class="file-size">${entry.isDir ? '' : formatSize(entry.size)}</span>
            </div>
        `).join('');
        listEl.querySelectorAll('.modal-file-item').forEach(el => {
            el.addEventListener('click', async () => {
                const path = el.dataset.path;
                const name = el.dataset.name;
                const isDir = el.dataset.dir === 'true';
                if (isDir) {
                    renderFileBrowser(path);
                } else {
                    fileBrowserSelectedPath = path;
                    document.getElementById('fileBrowserSelected').textContent = path.split('/').pop();
                    document.getElementById('fileBrowserSelect').disabled = false;
                    listEl.querySelectorAll('.modal-file-item').forEach(i => i.classList.remove('selected'));
                    el.classList.add('selected');
                }
            });
        });
    })();
}

function formatSize(bytes) {
    if (bytes < 1024) return `${bytes}B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
    return `${(bytes / 1024 / 1024).toFixed(1)}MB`;
}

function renderFileBrowserForImages(dir) {
    if (dir === '/storage/emulated/0' || dir === '/storage/emulated') dir = '/storage/emulated/0';
    fileBrowserPath = dir;
    document.getElementById('fileBrowserPath').textContent = dir;
    const listEl = document.getElementById('fileBrowserList');
    listEl.innerHTML = '<div class="loading-spinner">' + __('scope.loading') + '</div>';
    fileBrowserSelectedPath = null;
    document.getElementById('fileBrowserSelect').disabled = true;
    document.getElementById('fileBrowserSelected').textContent = __('keybox.no_selection');
    (async () => {
        const all = await listDir(dir);
        const imageExts = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp'];
        const images = all.filter(e => !e.isDir && imageExts.some(ext => e.name.toLowerCase().endsWith(ext)));
        const dirs = all.filter(e => e.isDir);
        const filtered = [...dirs, ...images];
        fileBrowserEntries = filtered;
        if (filtered.length === 0) { listEl.innerHTML = '<div class="loading-spinner">' + __('keybox.no_image_dir') + '</div>'; return; }
        listEl.innerHTML = filtered.map(entry => `
            <div class="modal-file-item ${entry.isDir ? 'dir-item' : ''}" data-path="${entry.fullPath}" data-name="${entry.name}" data-dir="${entry.isDir}">
                <span class="file-icon">${entry.isDir ? '📁' : '🖼️'}</span>
                <span class="file-name-text">${entry.name}</span>
                <span class="file-size">${entry.isDir ? '' : formatSize(entry.size)}</span>
            </div>
        `).join('');
        listEl.querySelectorAll('.modal-file-item').forEach(el => {
            el.addEventListener('click', async () => {
                const path = el.dataset.path;
                const name = el.dataset.name;
                const isDir = el.dataset.dir === 'true';
                if (isDir) {
                    renderFileBrowserForImages(path);
                } else {
                    fileBrowserSelectedPath = path;
                    document.getElementById('fileBrowserSelected').textContent = path.split('/').pop();
                    document.getElementById('fileBrowserSelect').disabled = false;
                    listEl.querySelectorAll('.modal-file-item').forEach(i => i.classList.remove('selected'));
                    el.classList.add('selected');
                }
            });
        });
    })();
}

async function deployKeyboxFromPath(path) {
    const progressEl = document.getElementById('uploadProgress');
    const fillEl = document.getElementById('upProgressFill');
    const textEl = document.getElementById('upProgressText');
    progressEl.classList.remove('hidden');
    fillEl.style.width = '30%';
    textEl.textContent = __('keybox.reading_file');
    log(__('log.reading_keybox', {path: path}));

    const r = await exec(`cat "${path}" 2>/dev/null`, {});
    if (r.errno !== 0 || !r.stdout.trim()) {
        progressEl.classList.add('hidden');
        textEl.textContent = '';
        showToast(__('keybox.toast_read_failed'));
        log(__('log.read_file_failed'), 'error');
        return;
    }

    const content = r.stdout;
    if (!looksLikeKeybox(content)) {
        progressEl.classList.add('hidden');
        fillEl.style.width = '0%';
        showToast(__('keybox.toast_invalid_file'));
        log(__('log.invalid_keybox'), 'error');
        return;
    }

    fillEl.style.width = '60%';
    textEl.textContent = __('keybox.deploying');
    await exec(`cp "${path}" ${KEYBOX_PATH} 2>/dev/null`, {});
    await exec(`mkdir -p /data/misc/keystore/omk && cp "${path}" ${OMK_DATA_KEYBOX} 2>/dev/null`, {});
    await exec(`cp ${KEYBOX_PATH} ${KEYBOX_BACKUP_PATH} 2>/dev/null`, {});
    fillEl.style.width = '100%';
    textEl.textContent = __('keybox.deploy_done');
    log(__('log.keybox_deployed'), 'success');
    showToast(__('keybox.toast_imported'));
    document.getElementById('fileNameDisplay').classList.add('hidden');
    document.getElementById('btnUploadKeybox').classList.add('hidden');
    await checkKeyboxStatus();
    setTimeout(() => { progressEl.classList.add('hidden'); fillEl.style.width = '0%'; }, 1500);
}

function openFileBrowser() {
    document.getElementById('fileBrowserModal').style.display = 'flex';
    fileBrowserSelectedPath = null;
    document.getElementById('fileBrowserSelect').disabled = true;
    document.getElementById('fileBrowserSelected').textContent = __('keybox.no_selection');
    renderFileBrowser('/storage/emulated/0');
}

function closeFileBrowser() {
    document.getElementById('fileBrowserModal').style.display = 'none';
}

/* ===== Service Control ===== */

async function checkDaemonStatus() {
    const keymintPid = await sh(`cat ${STATE_DIR}/keymint-daemon.pid 2>/dev/null`);
    const injectorPid = await sh(`cat ${STATE_DIR}/injector-daemon.pid 2>/dev/null`);
    const keymintRunning = keymintPid.stdout.trim() ? (await sh(`kill -0 ${keymintPid.stdout.trim()} 2>/dev/null && echo yes || echo no`)).stdout.trim() === 'yes' : false;
    const injectorRunning = injectorPid.stdout.trim() ? (await sh(`kill -0 ${injectorPid.stdout.trim()} 2>/dev/null && echo yes || echo no`)).stdout.trim() === 'yes' : false;
    const keymintEl = document.getElementById('keymintDaemonStatus');
    const injectorEl = document.getElementById('injectorDaemonStatus');
    keymintEl.textContent = keymintRunning ? __('controls.running') : __('controls.stopped');
    keymintEl.className = 'daemon-state ' + (keymintRunning ? 'running' : 'stopped');
    injectorEl.textContent = injectorRunning ? __('controls.running') : __('controls.stopped');
    injectorEl.className = 'daemon-state ' + (injectorRunning ? 'running' : 'stopped');
}

async function restartKeymint() { log(__('log.restarting_keymint')); await sh(`touch ${STATE_DIR}/restart.keymint`); log(__('log.restarting_keymint') + ' signal sent', 'success'); showToast(__('toast.keymint_restarting')); setTimeout(checkDaemonStatus, 2000); }
async function restartInjector() { log(__('log.restarting_injector')); await sh(`touch ${STATE_DIR}/restart.injector`); log(__('log.restarting_injector') + ' signal sent', 'success'); showToast(__('toast.injector_restarting')); setTimeout(checkDaemonStatus, 2000); }
async function restartAll() { log(__('log.restarting_all')); await sh(`touch ${STATE_DIR}/restart.all`); log(__('log.restarting_all') + ' signal sent', 'success'); showToast(__('toast.all_restarting')); setTimeout(checkDaemonStatus, 2000); }

async function killGms() {
    log(__('log.killing_gms'));
    await sh('for p in $(pgrep -f com.google.android.gms); do kill -9 $p 2>/dev/null; done; for p in $(pgrep -f com.google.android.gsf); do kill -9 $p 2>/dev/null; done; for p in $(pgrep -f com.android.vending); do kill -9 $p 2>/dev/null; done; echo "done"');
    log(__('log.gms_killed'), 'success');
    showToast(__('toast.gms_killed'));
}

async function fullDeploy() {
    log(__('log.full_deploy_start'));
    log(__('log.step1')); await syncToFile();
    log(__('log.step2')); await sh(`touch ${STATE_DIR}/restart.all`);
    log(__('log.step3')); await sh('for p in $(pgrep -f com.google.android.gms); do kill -9 $p 2>/dev/null; done; for p in $(pgrep -f com.google.android.gsf); do kill -9 $p 2>/dev/null; done; for p in $(pgrep -f com.android.vending); do kill -9 $p 2>/dev/null; done;');
    log(__('log.step4'));
    setTimeout(async () => { await checkDaemonStatus(); log(__('log.full_deploy_done'), 'success'); showToast(__('toast.full_deploy_done')); }, 2000);
}

/* ===== Tab Navigation ===== */

function initTabs() {
    document.querySelectorAll('.tab-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('.tab-btn').forEach(b => { b.classList.remove('active'); b.setAttribute('aria-selected', 'false'); });
            btn.classList.add('active'); btn.setAttribute('aria-selected', 'true');
            const tab = btn.dataset.tab;
            document.querySelectorAll('.tab-content').forEach(tc => tc.classList.remove('active'));
            document.getElementById(`tab-${tab}`).classList.add('active');
        });
    });
}

/* ===== Init ===== */

async function init() {
    log(__('log.init'));
    try { await enableEdgeToEdge(true); } catch (e) { /* ignore */ }
    initTabs();
    await loadInjectorConfig();
    renderPkgList();
    updateStats();
    await checkKeyboxStatus();
    await checkDaemonStatus();
    document.getElementById('statusBadge').textContent = __('header.ready');

    // Tab 1: Package Management
    document.getElementById('btnAddPkg').addEventListener('click', async () => {
        const input = document.getElementById('pkgInput');
        const pkg = input.value.trim();
        if (!pkg) { showToast(__('toast.pkg_enter')); return; }
        if (currentScoop.includes(pkg)) { showToast(__('toast.pkg_exists')); return; }
        currentScoop.push(pkg);
        input.value = '';
        if (document.getElementById('pkgSearch').value) document.getElementById('pkgSearch').value = '';
        renderPkgList(); updateStats(); showToast(__('toast.pkg_added', {pkg: pkg})); await syncToFile();
    });
    document.getElementById('btnAddDeny').addEventListener('click', async () => {
        const input = document.getElementById('denyPkgInput');
        const pkg = input.value.trim();
        if (!pkg) { showToast(__('toast.pkg_enter')); return; }
        if (!currentScoop.includes(pkg)) currentScoop.push(pkg);
        if (!currentDeny.includes(pkg)) currentDeny.push(pkg);
        input.value = '';
        if (document.getElementById('pkgSearch').value) document.getElementById('pkgSearch').value = '';
        renderPkgList(); updateStats(); showToast(__('toast.pkg_denied', {pkg: pkg})); await syncToFile();
    });
    document.getElementById('pkgSearch').addEventListener('input', (e) => { renderPkgList(e.target.value); });
    document.getElementById('btnRefreshList').addEventListener('click', () => { document.getElementById('pkgSearch').value = ''; renderPkgList(); });
    document.getElementById('btnApplyScope').addEventListener('click', applyScope);
    document.getElementById('btnResetScope').addEventListener('click', resetToAllApps);
    document.getElementById('pkgInput').addEventListener('keypress', (e) => { if (e.key === 'Enter') document.getElementById('btnAddPkg').click(); });
    document.getElementById('denyPkgInput').addEventListener('keypress', (e) => { if (e.key === 'Enter') document.getElementById('btnAddDeny').click(); });

    // Tab 2: Keybox
    document.getElementById('btnDownloadKeybox').addEventListener('click', () => { downloadKeyboxFromUrl(document.getElementById('keyboxUrlInput').value.trim()); });
    document.getElementById('keyboxUrlInput').addEventListener('keypress', (e) => { if (e.key === 'Enter') document.getElementById('btnDownloadKeybox').click(); });
    document.getElementById('btnPasteKeybox').addEventListener('click', () => { pasteKeybox(document.getElementById('keyboxTextArea').value); });
    document.getElementById('fileUploadArea').addEventListener('click', openFileBrowser);
    document.getElementById('fileBrowserClose').addEventListener('click', closeFileBrowser);
    document.getElementById('fileBrowserSelect').addEventListener('click', async () => {
        if (!fileBrowserSelectedPath) return;
        closeFileBrowser();
        document.getElementById('fileNameDisplay').textContent = `📄 ${fileBrowserSelectedPath.split('/').pop()}`;
        document.getElementById('fileNameDisplay').classList.remove('hidden');
        document.getElementById('btnUploadKeybox').classList.remove('hidden');
    });
    document.getElementById('btnUploadKeybox').addEventListener('click', async () => {
        if (fileBrowserSelectedPath) {
            await deployKeyboxFromPath(fileBrowserSelectedPath);
            fileBrowserSelectedPath = null;
            document.getElementById('fileNameDisplay').classList.add('hidden');
            document.getElementById('btnUploadKeybox').classList.add('hidden');
        }
    });
    document.getElementById('fileBrowserSearch').addEventListener('input', () => { renderFileBrowser(fileBrowserPath); });

    // Tab 3: Service Control
    document.getElementById('btnRefreshStatus').addEventListener('click', checkDaemonStatus);
    document.getElementById('btnRestartKeymint').addEventListener('click', restartKeymint);
    document.getElementById('btnRestartInjector').addEventListener('click', restartInjector);
    document.getElementById('btnRestartAll').addEventListener('click', restartAll);
    document.getElementById('btnKillGms').addEventListener('click', killGms);
    document.getElementById('btnSetScopeOnly').addEventListener('click', applyScope);
    document.getElementById('btnDeployAll').addEventListener('click', fullDeploy);
    document.getElementById('btnClearLog').addEventListener('click', () => { document.getElementById('logOutput').innerHTML = '<div class="log-empty">' + __('controls.log_ready') + '</div>'; });

    // Tab 4: About
    document.getElementById('linkGithub').addEventListener('click', (e) => { e.preventDefault(); exec('am start -a android.intent.action.VIEW -d "https://github.com/yourbestregard/AzmunaasToolbox"', {}); });
    document.getElementById('linkTelegram').addEventListener('click', (e) => { e.preventDefault(); exec('am start -a android.intent.action.VIEW -d "https://t.me/yuriiroot"', {}); });

    // Background Image
    const BG_KEY = 'omk_webui_bg';

    function applyBg(url) {
        if (!url) {
            document.body.classList.remove('has-bg');
            document.body.style.backgroundImage = '';
            document.getElementById('bgPreview').classList.remove('has-bg');
            document.getElementById('bgPreview').style.backgroundImage = '';
            document.getElementById('bgPreview').innerHTML = '<span class="bg-placeholder">' + __('about.no_bg') + '</span>';
            localStorage.removeItem(BG_KEY);
            return;
        }
        document.body.style.backgroundImage = `url('${url}')`;
        document.body.classList.add('has-bg');
        document.getElementById('bgPreview').style.backgroundImage = `url('${url}')`;
        document.getElementById('bgPreview').classList.add('has-bg');
        document.getElementById('bgPreview').innerHTML = '';
        localStorage.setItem(BG_KEY, url);
    }

    const savedBg = localStorage.getItem(BG_KEY);
    if (savedBg) applyBg(savedBg);

    document.getElementById('btnSetBgUrl').addEventListener('click', () => {
        const url = document.getElementById('bgUrlInput').value.trim();
        if (!url) { showToast(__('about.bg_url_placeholder')); return; }
        applyBg(url);
        document.getElementById('bgUrlInput').value = '';
        showToast(__('about.bg_set'));
    });
    document.getElementById('bgUrlInput').addEventListener('keypress', (e) => {
        if (e.key === 'Enter') document.getElementById('btnSetBgUrl').click();
    });
    document.getElementById('btnClearBg').addEventListener('click', () => {
        applyBg(null);
        showToast(__('about.bg_cleared'));
    });

    document.getElementById('bgFileArea').addEventListener('click', () => {
        document.getElementById('fileBrowserModal').style.display = 'flex';
        fileBrowserSelectedPath = null;
        document.getElementById('fileBrowserSelect').disabled = true;
        document.getElementById('fileBrowserSelected').textContent = __('keybox.no_selection');
        const origHandler = document.getElementById('fileBrowserSelect').onclick;
        document.getElementById('fileBrowserSelect').onclick = async () => {
            if (!fileBrowserSelectedPath) return;
            const path = fileBrowserSelectedPath;
            closeFileBrowser();
            const bgDir = '/data/adb/modules/oh_my_keymint/webui';
            await exec(`mkdir -p ${bgDir} && cp "${path}" ${bgDir}/background.jpg 2>/dev/null`, {});
            const bgUrl = `file://${bgDir}/background.jpg`;
            applyBg(bgUrl);
            showToast(__('about.bg_set'));
            document.getElementById('fileBrowserSelect').onclick = origHandler;
        };
        renderFileBrowserForImages('/storage/emulated/0');
    });

    log(__('log.init_done'), 'success');
}

document.addEventListener('DOMContentLoaded', init);
